test:
	vector test --config-yaml resource/config.yaml
validate:
	VECTOR_SELF_NODE_NAME= KUBERNETES_SERVICE_HOST= KUBERNETES_SERVICE_PORT=4321 vector -v validate --config-yaml resource/vector-config.yaml
